### ISSUE TITLE
Devops task list for 1KGenome reference server

### ISSUE THREAD

**Issue by kozbo** [BD2KGenomics/ga4gh-integration#8]
Our Genomic Analysis milestone includes providing a GA4GH reference server running on top of the 1000 Genome data set. This will require many changes in the code base but it will also require some basic devops work to set up the server in a way that is usable AND supportable. There are certain things we need to do to make sure that we limit expenses and simplify support. Here is a task list that we can work through:
- [x] Support email list: Add an email link on the landing page (along with the text email address to report bugs)
- [x] Monitoring: how do we monitor the cost of running the server? Are there alerts that we can configure?
- [x] Documentation: What documentation is required? 
- [x] Sample code: we should develop and provide some simple sample code
- [x] Logging: 
  - [x] Who is accessing the server

**Comment by david4096** [comment]
Re: documentation, some description of the 1000 genomes dataset with links to more data would be helpful to include on the landing page.

Landing page
- Information about GA4GH in general
- Links to github repos
- Link to support email
- Some details about 1kg, link to 1kg
- Link to example code

**Comment by kozbo** [comment]
Not sure how I managed to create a duplicate issue here but this is the same as #9 Closing!
