### ISSUE TITLE
Devops task list for 1KGenome reference server

### ISSUE THREAD

**Issue by kozbo** [BD2KGenomics/ga4gh-integration#9]
Our Genomic Analysis milestone includes providing a GA4GH reference server running on top of the 1000 Genome data set. This will require many changes in the code base but it will also require some basic devops work to set up the server in a way that is usable AND supportable. There are certain things we need to do to make sure that we limit expenses and simplify support. Here is a task list that we can work through:
- [x] Support email list: Add an email link on the landing page (along with the text email address to report bugs)
- [x] Monitoring: how do we monitor the cost of running the server? Are there alerts that we can configure?
- [x] Documentation: What documentation is required? 
- [x] Sample code: we should develop and provide some simple sample code
- [x] Logging: 
  - [x] Who is accessing the server 
  - [x] What are they doing
  - [x] Capture errors and other output from the ref server
- [x] Security: Set up robots.txt and other basic configuration options

**Comment by kozbo** [comment]
Updated documentation for apache configuration PR #1131
Sufficient logging added in PR #1099
Email list has been created and email address added to landing page (bug #1121)
l am still trying to figure out how to attach an alert to the expenses incurred by the server...
I wonder if we could consider the swagger docs sufficient for the sample code requirement?

**Comment by kozbo** [comment]
Monitoring of expenses can be done here: https://ea.azure.com/
We added some sample code and an iPython notebook to the server
Robots.txt has also been added
Closing
